Write a program that will find all numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a list.
Hint: Consider using the range(#begin, #end) method.

In [ ]:
final_list = []
for i in range(2000,3201):
  if i % 7 == 0 and i % 5 != 0:
    final_list.append(i)


print(final_list)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [ ]:
def factorial(n):

    if n == 0:
        return 1

    return n * factorial(n-1)



In [ ]:
num = 5;
print("Factorial of", num, "is",
factorial(num))

Factorial of 5 is 120


In [18]:
# declaring a string variable
str = "Geeksforgeeks is fun."

# index to remove character at
n = 4

# declaring an empty string variable for storing modified string
modified_str = ''

# iterating over the string
for char in range(0, len(str)):

    # checking if the char index is equivalent to n
    if(char != n):
        # append original string character
        modified_str += str[char]

In [19]:
print("Modified string after removing ", n, "th character ")
print(modified_str)

Modified string after removing  4 th character 
Geekforgeeks is fun.


In [21]:

# import module
import numpy as np

# create array
print("\nArray:")
arr = np.array([1, 2, 4, 5])
print(arr)
print(type(arr))

# apply method
lis = arr.tolist()

# display list
print("\nList:")
print(lis)
print(type(lis))


Array:
[1 2 4 5]
<class 'numpy.ndarray'>

List:
[1, 2, 4, 5]
<class 'list'>


In [22]:
# import module
import numpy as np

# create array
print("\nArray:")
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr)
print(type(arr))

# apply method
lis = arr.tolist()

# display list
print("\nList:")
print(lis)
print(type(lis))


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>

List:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [23]:
# Python program to find roots
# of a quadratic equation
import math

# Prints roots of quadratic equation
# ax*2 + bx + x
def findRoots(a, b, c):

    # If a is 0, then equation is
    # not quadratic, but linear
    if a == 0:
        print("Invalid")
        return -1
    d = b * b - 4 * a * c
    sqrt_val = math.sqrt(abs(d))

    if d > 0:
        print("Roots are real and different ")
        print((-b + sqrt_val)/(2 * a))
        print((-b - sqrt_val)/(2 * a))
    elif d == 0:
        print("Roots are real and same")
        print(-b / (2*a))
    else:  # d<0
        print("Roots are complex")
        print(- b / (2*a), " + i", sqrt_val / (2 * a))
        print(- b / (2*a), " - i", sqrt_val / (2 * a))

In [24]:
# Driver Program
if __name__ == '__main__':
    a = 1
    b = -7
    c = 12

    # Function call
    findRoots(a, b, c)


Roots are real and different 
4.0
3.0
